kind: pipeline
name: default

steps:
- name: test-backend
  group: tests
  image: node:latest
  commands:
  - cd packages/xkcd-proxy-server
  - npm install
  - npm run format -- -c
  - npm run lint
  # Set environment to test
  - export NODE_ENV=test
  - npm run test
  - npm run test:e2e

- name: test-frontend
  group: tests
  image: node:latest
  commands:
  - cd packages/xkcd-proxy-client
  - npm install
  - npm run test

- name: build-backend
  image: plugins/docker
  settings:
    repo: manishdigithinkit/xkcd-proxy-server
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: packages/xkcd-proxy-server/Dockerfile
    context: packages/xkcd-proxy-server
    tags:
      - edge
  # when:
  #   event:
  #     - push
  #   branch:
  #     - staging

- name: build-frontend
  image: plugins/docker
  settings:
    repo: manishdigithinkit/xkcd-proxy-client
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: packages/xkcd-proxy-client/Dockerfile
    context: packages/xkcd-proxy-client
    tags:
      - edge
  # when:
  #   event:
  #     - push
  #   branch:
  #     - staging
