kind: pipeline
name: default

steps:
- name: test-backend
  group: tests
  image: node:latest
  commands:
  - cd packages/xkcd-proxy-server
  - npm install
  - npm run format -- -c
  - npm run lint
  # Set environment to test
  - export NODE_ENV=test
  - npm run test
  - npm run test:e2e

- name: test-frontend
  group: tests
  image: node:latest
  commands:
  - cd packages/xkcd-proxy-client
  - npm install
  - npm run test
